### ISSUE TITLE
Use and get data store

### ISSUE THREAD

**Issue by kamalkech** [elcobvg/sapper-store#3]
```
this.store.dispatch('addItem', value);
this.store.commit('CLEAR_ITEM', index);
```
get this error :

```
 TypeError: Cannot read property 'store' of undefined
```

this not working at all, any idea >

**Comment by elcobvg** [comment]
It may well be that it is no longer compatible. Sapper has gone through a lot of changes since I wrote this package. Unfortunately I don't have the time to update this at the moment, sorry.

**Comment by kamalkech** [comment]
ok understood
